remote_theme: "jekyll/minima"

title: TV Tracking - Cinematic Universe Information
description: A place for me to write up my summaries of the best way to absorb the Cinematic Universes I think are great.

minima:
  nav_pages:
    - babylon-5/babylon-5.md
    - mcu/README.md
    - red-dwarf/README.md
    - stargate/README.md
    - star-trek/README.md
    - star-wars/README.md
